### PR TITLE
View Layouts for Frontend Pages #60

### PR DESCRIPTION
**Pull request by drewroberts**

### CODE REVIEW

**Comment by pdbreen** [comment]
Is there more documentation somewhere on the big picture?  There's not enough in issue #60 to fully understand what you are trying to achieve or how all of this would work in Laravel.

**Comment by drewroberts** [comment]
@pdbreen Could you add a type on Layout with Enum so that each model can have its own Layout designs? We'll need the following in here:

- Page
- Post
- Topic
- Series

Could other packages then add new Types to that list for the models in their packages that need layouts?

I'll create stub Layouts for each of those models in the views directory and will also add them in data migration in the regular migrations folder.

**Comment by pdbreen** [comment]
Added `LayoutManager` singleton (and facade) along with a LayoutViewCreator that allow establishing a layout context for the view and making sure context is injected in every view.   Will add testing after some different layouts are added.

**Comment by drewroberts** [comment]
@pdbreen THANK YOU! I kept tripping over myself with this code.

**Pull request merged**
